version: '3.9'

services:
  postgres-db1:
    container_name: postgres1
    image: postgres
    environment:
      - POSTGRES_USER=${PDB_USER}
      - POSTGRES_PASSWORD=${PDB_PASSWORD}
      - POSTGRES_DB=${PDB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - sales
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - sales
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres-db1
    command: ["-path", "/migrations", "-database" ,"postgres://${PDB_USER}:${PDB_PASSWORD}@postgres-db1:${PDB_PORT}/${PDB_NAME}?sslmode=disable","up"]


  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - sales
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
  

  saleservice:
    container_name: sale
    build: .
    ports:
      - "50052:50052"
    networks:
      - sales
    depends_on:
      postgres-db1:
        condition: service_healthy
      mongo:
        condition: service_healthy



networks:
  sales:
    external: true

volumes:
  db:
  mongo_data:
  