version: '3.9'

services:
  postgres-db1:
    container_name: postgres1
    image: postgres
    environment:
      - POSTGRES_USER=${PDB_USER}
      - POSTGRES_PASSWORD=${PDB_PASSWORD}
      - POSTGRES_DB=${PDB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - sales
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    networks:
      - sales
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres-db1
    command: ["-path", "/migrations", "-database" ,"postgres://${PDB_USER}:${PDB_PASSWORD}@postgres-db1:${PDB_PORT}/${PDB_NAME}?sslmode=disable","up"]


  mongodb:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example 
    volumes:
      - db2:/var/lib/mongosh/data
    networks:
      - sales
  

  saleservice:
    container_name: sale
    build: .
    ports:
      - "50052:50052"
    networks:
      - sales
    depends_on:
      - mongodb
      - postgres-db1



networks:
  sales:
    external: true

volumes:
  db:
  db2:
  